---
- name: Check if git exists.
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.git"
  register: result

- name: Clone/update dots.
  ansible.builtin.git:
    clone: "{{ not result.stat.exists }}"
    dest: "{{ (not result.stat.exists) | ternary(ansible_env.HOME + '/dots', ansible_env.HOME) }}"
    repo: https://github.com/SCThijsse/dots.git
    version: master
    force: true
  changed_when: not result.stat.exists

- name: Install dots.
  block:
    - name: Clone dots.
      ansible.builtin.git:
        dest: "{{ ansible_env.HOME }}/dots"
        repo: https://github.com/SCThijsse/dots.git
        version: master

    - name: Find dots.
      ansible.builtin.find:
        paths: "{{ ansible_env.HOME }}/dots"
        file_type: any
        hidden: true
      register: register

    - name: Move dots.
      ansible.builtin.copy:
        remote_src: true
        src: "{{ item.path }}"
        dest: "{{ ansible_env.HOME }}"
        mode: "{{ '0755' if item.isdir else '0644' }}"
      loop: "{{ register.files }}"

    - name: Remove old dots folder.
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/dots"
        state: absent
  when: not result.stat.exists

- name: Create .zprofile symlink.
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.profile"
    dest: "{{ ansible_env.HOME }}/.zprofile"
    state: link
