---
- name: Install firefox.
  become: true
  ansible.builtin.pacman:
    name: "{{ firefox_package }}"
    state: present
    update_cache: true

- name: Clone SimplerentFox.
  ansible.builtin.git:
    dest: "{{ ansible_env.HOME }}/Software/SimpleFox"
    repo: https://github.com/SCThijsse/SimpleFox.git
    version: master
    update: "{{ firefox_redo }}"
    force: "{{ firefox_redo }}"

- name: Add remote upstream to git repository.  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: "git remote add upstream https://github.com/migueravila/SimpleFox"
    chdir: "{{ ansible_env.HOME }}/Software/SimpleFox"
  register: add_result
  changed_when: add_result.rc == 0
  failed_when:
    - add_result.rc != 0
    - add_result.stderr | default('') is not search("remote .* already exists")

- ansible.builtin.include_tasks:
    file: profile.yml
  loop: "{{ firefox_profiles }}"
  loop_control:
    extended: true
