---
- name: "Create profile {{ item.name }}."
  ansible.builtin.command:
    cmd: "firefox-developer-edition -no-remote -CreateProfile {{ item.name }} --headless"
  changed_when: false

- name: Get profile path from profiles.ini.
  ansible.builtin.command:
    cmd: "egrep '^Path=.*\\.{{ item.name }}(-[0-9]+)?$' {{ firefox_profiles_path }}"
  changed_when: false
  register: grep_result

- name: Set profile path from profiles.ini.
  ansible.builtin.set_fact:
    profile_path: "{{ grep_result.stdout | split('=') | last }}"

- name: Install custom css.
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.mozilla/firefox/{{ profile_path }}"
    src: "{{ ansible_env.HOME }}/Software/SimpleFox/chrome"
    remote_src: true
    mode: 0755

- name: Check if prefs.js exists.
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.mozilla/firefox/{{ profile_path }}/prefs.js"
  register: stat_result

- name: Check if prefs.js exists (cont).
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.mozilla/firefox/{{ profile_path }}/prefs.js"
    state: "{{ 'touch' if not stat_result.stat.exists else 'file' }}"
    mode: 0644

- name: Set user preferences.
  ansible.builtin.lineinfile:
    dest: "{{ ansible_env.HOME }}/.mozilla/firefox/{{ profile_path }}/prefs.js"
    regexp: '^user_pref\("{{ pref.name }}", \s*\S+?\);'
    # yamllint disable-line rule:line-length
    line: "user_pref(\"{{ pref.name }}\", {{ '\"%s\"' | format(pref.value) if item.value is string else (pref.value | lower) }});"
    state: present
  loop_control:
    loop_var: pref
  loop: "{{ item.prefs }}"
