---
- name: Install unzip.
  become: true
  ansible.builtin.pacman:
    name: unzip
    state: present
    update_cache: true
  tags: [molecule-idempotence-notest]

- ansible.builtin.include_tasks: shellcheck.yml
