---
- name: Install unzip.
  become: true
  ansible.builtin.pacman:
    name: unzip
    state: present
    update_cache: true
  notify:
    - uninstall lua dependencies

- ansible.builtin.include_tasks: shellcheck.yml
