---
- name: Install tar.
  become: true
  ansible.builtin.pacman:
    name: tar
    state: present
    update_cache: true

- name: Check if shellcheck binary exists.
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/bin/shellcheck"
  register: shellcheck_check

- name: Check lua-language-server version.
  ansible.builtin.command: "{{ shellcheck_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: shellcheck_existing_version

- name: Install shellcheck.
  when: >
    not shellcheck_check.stat.exists
    or shellcheck_version not in shellcheck_existing_version.stdout
  block:
    - name: Get shellcheck zip.
      ansible.builtin.get_url:
        # yamllint disable-line rule:line-length
        url: "{{ shellcheck_repo_path }}/releases/download/v{{ shellcheck_version }}/shellcheck-v{{ shellcheck_version }}.linux.x86_64.tar.xz"
        dest: /tmp
        mode: 0644
      register: shellcheck_zip

    - name: Unarchive shellcheck.
      ansible.builtin.unarchive:
        src: "{{ shellcheck_zip.dest }}"
        dest: "{{ shellcheck_bin_path | dirname }}"
        remote_src: true
        extra_opts: [--strip-components=1, "shellcheck-v{{ shellcheck_version }}/shellcheck"]
        mode: 0755

    - name: Cleanup tar.
      ansible.builtin.file:
        path: "{{ shellcheck_zip.dest }}"
        state: absent
