---
- name: Check if golangci-lint binary exists.
  ansible.builtin.stat:
    path: "{{ golangcilint_bin_path }}"
  register: golangcilint_check

- name: Check golangci-lint version.
  ansible.builtin.command: "{{ golangcilint_bin_path }} version"
  failed_when: false
  changed_when: false
  register: golangcilint_existing_version

- name: Install golangci-lint.
  when: >
    not golangcilint_check.stat.exists
    or golangcilint_version not in golangcilint_existing_version.stdout
  block:
    - name: Set sha256 checksum url.
      ansible.builtin.set_fact:
        # yamllint disable-line rule:line-length
        golangcilint_checksum_url: "{{ golangcilint_repo_path }}/releases/download/v{{ golangcilint_version }}/golangci-lint-{{ golangcilint_version }}-checksums.txt"

    - name: Get sha256 checksum.
      ansible.builtin.set_fact:
        golangcilint_checksums: "{{ lookup('url', golangcilint_checksum_url, split_lines=False) }}"
        # yamllint disable-line rule:line-length
        golangcilint_file_name: "{{ 'golangci-lint-' + golangcilint_version + '-' + golangcilint_platform + '-' + golangcilint_arch + '.tar.gz' }}"

    - name: Bar.
      ansible.builtin.set_fact:
        # yamllint disable-line rule:line-length
        golangcilint_checksum: "{{ golangcilint_checksums | regex_search('(.*)' + golangcilint_file_name, miltiline=True) | split(' ') | first | trim }}"

    - name: Get golangci-lint tar.
      ansible.builtin.get_url:
        # yamllint disable-line rule:line-length
        url: "{{ golangcilint_repo_path }}/releases/download/v{{ golangcilint_version }}/{{ golangcilint_file_name }}"
        dest: /tmp
        checksum: "sha256:{{ golangcilint_checksum }}"
        mode: 0644
      register: golangcilint_tar

    - name: Unarchive golangci-lint.
      ansible.builtin.unarchive:
        src: "{{ golangcilint_tar.dest }}"
        dest: /tmp
        remote_src: true
        mode: 0755

    - name: Install golangci-lint.
      become: true
      ansible.builtin.copy:
        # yamllint disable-line rule:line-length
        src: "/tmp/golangci-lint-{{ golangcilint_version }}-{{ golangcilint_platform }}-{{ golangcilint_arch }}/golangci-lint"
        dest: "{{ golangcilint_bin_path }}"
        remote_src: true
        mode: 0755
        owner: root
        group: root

    - name: Cleanup tar and unarchived folders.
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ golangcilint_tar.dest }}"
        - "/tmp/{{ golangcilint_platform }}-golangcilint_arch }}"
