---
- name: Install go & gopls.
  become: true
  ansible.builtin.pacman:
    name:
      - go
      - gopls
    state: present

# - ansible.builtin.include_tasks: earthly.yml
- ansible.builtin.include_tasks: golangcilint.yml
