---
- name: Check if kubectl binary exists.
  ansible.builtin.stat:
    path: "{{ kubectl_bin_path }}"
  register: kubectl_check

- name: Check kubectl version.
  ansible.builtin.command: "{{ kubectl_bin_path }} version"
  failed_when: false
  changed_when: false
  register: kubectl_existing_version

- name: Install kubectl.
  when: >
    not kubectl_check.stat.exists
    or kubectl_version not in kubectl_existing_version.stdout
  block:
    - name: Set sha256 checksum url of latest stable version.
      ansible.builtin.set_fact:
        # yamllint disable-line rule:line-length
        kubectl_checksum_url: "{{ kubectl_repo_path }}/{{ kubectl_version }}/bin/{{ kubectl_platform }}/{{ kubectl_arch }}/kubectl.sha256"

    - name: Get sha256 checksum of latest stable version.
      ansible.builtin.set_fact:
        kubectl_checksum: "{{ lookup('url', kubectl_checksum_url, split_lines=False) | trim | split(' ') | first }}"

    - name: Get kubectl binary.
      ansible.builtin.get_url:
        url: "{{ kubectl_repo_path }}/{{ kubectl_version }}/bin/{{ kubectl_platform }}/{{ kubectl_arch }}/kubectl"
        dest: "{{ kubectl_bin_path }}"
        checksum: "sha256:{{ kubectl_checksum }}"
        mode: 0755
