---
- name: Check if minikube binary exists.
  ansible.builtin.stat:
    path: "{{ minikube_bin_path }}"
  register: minikube_check

- name: Check minikube version.
  ansible.builtin.command: "{{ minikube_bin_path }} version"
  failed_when: false
  changed_when: false
  register: minikube_existing_version

- name: Install minikube.
  when: >
    not minikube_check.stat.exists
    or minikube_version not in minikube_existing_version.stdout
  block:
    - name: Get minikube binary.
      ansible.builtin.get_url:
        # yamllint disable-line rule:line-length
        url: "{{ minikube_repo_path }}/minikube/releases/{{ minikube_version }}/minikube-{{ minikube_platform }}-{{ minikube_arch }}"
        dest: /tmp
        mode: 0755
      register: minikube_binary

    - name: Set sha256 checksum url.
      ansible.builtin.set_fact:
        # yamllint disable-line rule:line-length
        minikube_checksum_url: "{{ minikube_repo_path }}/minikube/releases/{{ minikube_version }}/minikube-{{ minikube_platform }}-{{ minikube_arch }}.sha256"

    - name: Get sha256 checksum.
      ansible.builtin.set_fact:
        minikube_checksum: "{{ lookup('url', minikube_checksum_url, split_lines=False) | trim | split(' ') | first }}"

    - name: Get checksum of downloaded minikube binary.
      ansible.builtin.stat:
        path: "{{ minikube_binary.dest }}"
        checksum_algorithm: sha256
        get_checksum: true
      register: result

    - name: Validate minikube binary checksum.
      ansible.builtin.assert:
        that:
          - minikube_checksum == result.stat.checksum

    - name: Install minikube.
      become: true
      ansible.builtin.copy:
        src: "{{ minikube_binary.dest }}"
        dest: "{{ minikube_bin_path }}"
        remote_src: true
        mode: 0755
        owner: root
        group: root
