---
- name: build eclipse.jdt.ls
  ansible.builtin.command:
    cmd: "mvn clean verify -B -DskipTests -Dmaven.repo.local={{ ansible_env.HOME }}/.cache/maven/repository"
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
  args:
    chdir: "{{ ansible_env.HOME }}/Software/eclipse.jdt.ls"

- name: build java-debug
  ansible.builtin.command:
    cmd: "mvn clean verify -B -Dmaven.repo.local={{ ansible_env.HOME }}/.cache/maven/repository"
    creates: "{{ ansible_env.HOME }}/Software/java-debug/com.microsoft.java.debug.plugin/target"
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
  args:
    chdir: "{{ ansible_env.HOME }}/Software/java-debug"

- name: build vscode-java-test
  ansible.builtin.command:
    cmd: "mvn clean verify -B -Dmaven.repo.local={{ ansible_env.HOME }}/.cache/maven/repository"
    creates: "{{ ansible_env.HOME }}/Software/vscode-java-test/server"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.config/nvm/versions/node/v{{ node_version }}/bin"
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
  args:
    chdir: "{{ ansible_env.HOME }}/Software/vscode-java-test/java-extension"
