---
- name: build eclipse.jdt.ls
  ansible.builtin.command:
    cmd: "mvn clean verify -B -DskipTests -Dmaven.repo.local={{ java_maven_repo }}"
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
  args:
    chdir: "{{ java_eclipse_git_dest }}"

- name: build java-debug
  ansible.builtin.command:
    cmd: "mvn clean verify -B -Dmaven.repo.local={{ java_maven_repo }}"
    creates: "{{ java_debug_git_dest }}/com.microsoft.java.debug.plugin/target"
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
  args:
    chdir: "{{ java_debug_git_dest }}"

- name: build vscode-java-test
  ansible.builtin.command:
    cmd: "mvn clean verify -B -Dmaven.repo.local={{ java_maven_repo }}"
    creates: "{{ java_test_git_dest }}/server"
  environment:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk
  args:
    chdir: "{{ java_test_git_dest }}/java-extension"
