---
- name: Check if lua-language-server binary exists.
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/bin/lua-language-server"
  register: lls_check

- name: Check lua-language-server version.
  ansible.builtin.command: "{{ lls_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: lls_existing_version

- name: Install lua-language-server.
  ansible.builtin.unarchive:
    # yamllint disable-line rule:line-length
    src: "{{ lls_repo_path }}/releases/download/{{ lls_version }}/lua-language-server-{{ lls_version }}-linux-x64.tar.gz"
    dest: "{{ lls_bin_path | dirname | dirname }}"
    remote_src: true
    mode: 0755
  register: lls_zip
  when: >
    not lls_check.stat.exists
    or lls_version not in lls_existing_version.stdout
