---
- name: Install unzip.
  become: true
  ansible.builtin.pacman:
    name: unzip
    state: present

- ansible.builtin.include_tasks: lua_language_server.yml
- ansible.builtin.include_tasks: selene.yml
- ansible.builtin.include_tasks: stylua.yml
