---
- name: "Ensure {{ selene_bin_path | dirname }} exists."
  ansible.builtin.file:
    path: "{{ selene_bin_path | dirname }}"
    state: directory
    mode: 0755

- name: Check if selene binary exists.
  ansible.builtin.stat:
    path: "{{ selene_bin_path }}"
  register: selene_check

- name: Check selene version.
  ansible.builtin.command: "{{ selene_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: selene_existing_version

- name: Install selene.
  ansible.builtin.unarchive:
    # yamllint disable-line rule:line-length
    src: "{{ selene_repo_path }}/releases/download/{{ selene_version }}/selene-{{ selene_version }}-{{ selene_platform }}.zip"
    dest: "{{ selene_bin_path | dirname }}"
    remote_src: true
    mode: 0755
  when: >
    not selene_check.stat.exists
    or selene_version not in selene_existing_version.stdout
