---
- name: "Find {{ tool.name }}."
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME + '/.local/bin/' + tool.name }}"
  register: result

- name: "Download {{ tool.name }}."
  ansible.builtin.get_url:
    dest: "{{ ansible_env.HOME + '/' + tool.name }}.zip"
    url: "{{ tool.repo_url + tool.download_url }}"
    force: "{{ lang_lua_force }}"
    mode: 0644
  when: not result.stat.exists or lang_lua_force

- name: "Unarchive {{ tool.name }}."
  ansible.builtin.unarchive:
    src: "{{ ansible_env.HOME + '/' + tool.name }}.zip"
    dest: "{{ tool.dest }}"
    remote_src: true
    creates: "{{ ansible_env.HOME + '/.local/bin/' + tool.name }}"
    extra_opts: "{{ tool.extra_opts | default([]) }}"
    mode: 0755

- name: "Remove zip {{ tool.name }}.zip."
  ansible.builtin.file:
    path: "{{ ansible_env.HOME + '/' + tool.name }}.zip"
    state: absent
