---
- name: Prepare
  hosts: all
  gather_facts: false

  vars:
    dots_git_dest: /root

  pre_tasks:
    - name: Update pacman cache.
      ansible.builtin.pacman:
        update_cache: true

  roles:
    - role: git
    - role: dots
