---
dependencies: []

galaxy_info:
  author: scthijsse
  description: Personal rust tools installer.
  license: "MIT"
  min_ansible_version: "2.4"
  platforms:
    - name: ArchLinux
      versions:
        - all
  galaxy_tags: []
