---
- name: build neovim
  become: true
  ansible.builtin.make:
    chdir: "{{ neovim_git_dest }}"
    target: install

- name: remove plugins
  ansible.builtin.file:
    path: "{{ neovim_plugin_dir }}"
    state: absent

- name: install neovim plugins
  ansible.builtin.command: |
    nvim --headless \
        -u "{{ neovim_bootstrap_config }}" \
        -c 'autocmd User PackerComplete quitall' \
        -c 'PackerSync'
