---
- name: Install python.
  become: true
  ansible.builtin.pacman:
    name: python
    state: present
    update_cache: true

- name: Install pip.
  ansible.builtin.command:
    cmd: python -m ensurepip --upgrade
    creates: /usr/bin/pip

- name: Check pip version.
  ansible.builtin.command: "/usr/bin/pip --version"
  failed_when: false
  changed_when: false
  register: pip_existing_version
