---
- name: Install dependencies.
  ansible.builtin.pacman:
    name: tmux
    state: present
    update_cache: true

- name: Clone .tmux.
  ansible.builtin.git:
    dest: "~/.config/tmux"
    repo: "https://github.com/SCThijsse/.tmux.git"
    version: master

- name: Create symlinks.
  ansible.builtin.file:
    src: "~/.config/tmux/{{ item }}"
    dest: "~/{{ item }}"
    state: link
  loop:
    - .tmux.conf
    - .tmux.conf.local
