---
- name: find patches
  ansible.builtin.find:
    paths: "{{ suckless_git_dest }}/{{ suckless_tool }}/patches"
  register: patches

- name: apply patches
  ansible.posix.patch:
    basedir: "{{ suckless_git_dest }}/{{ suckless_tool }}"
    src: "{{ item }}"
    remote_src: true
    strip: 1
    state: present
  loop: "{{ patches.files | map(attribute='path') | sort }}"

- name: build tool
  become: true
  ansible.builtin.make:
    chdir: "{{ suckless_git_dest }}/{{ suckless_tool }}"
    target: "{{ item }}"
  loop:
    - clean
    - install
