---
- name: Install java17.
  become: true
  ansible.builtin.pacman:
    name:
      - jdk17-openjdk
      - maven
    state: present

- name: Clone eclipse.jdt.ls.
  ansible.builtin.git:
    repo: https://github.com/eclipse/eclipse.jdt.ls
    dest: "{{ java_eclipse_git_dest }}"
    version: master
    force: true
  register: eclipse
  changed_when: eclipse.changed or java_force
  notify:
    - build eclipse.jdt.ls
  tags: [molecule-notest]

- name: Clone java-debug.
  ansible.builtin.git:
    repo: https://github.com/microsoft/java-debug
    dest: "{{ java_debug_git_dest }}"
    version: main
    force: true
  register: debug
  changed_when: debug.changed or java_force
  notify:
    - build java-debug

- name: Clone vscode-java-test.
  ansible.builtin.git:
    repo: https://github.com/microsoft/vscode-java-test
    dest: "{{ java_test_git_dest }}"
    version: main
    force: true
  register: test
  changed_when: test.changed or java_force
  notify:
    - build vscode-java-test

- name: Clone vscode-java-decompiler.
  ansible.builtin.git:
    repo: https://github.com/dgileadi/vscode-java-decompiler
    dest: "{{ java_decompiler_git_dest }}"
    version: master
    force: true
